- name: Uninstalling tmux
  make:
    target: uninstall
    chdir: "/opt/tmux-{{ tmux_local_version }}"
  become: yes

- name: Removing source folder
  become: true
  file:
    path: "/opt/tmux-{{ tmux_local_version }}"
    state: absent